### ISSUE TITLE
Youtube video linki

### ISSUE THREAD

**Issue by ozkansen** [mustafamuratcoskun/one-video-react#1]
Merhaba Murat hocam,

Readme dosyasına youtube video linkini ekleyebilirmisiniz.

Teşekkürler
İyi çalışmalar.

**Comment by mustafamuratcoskun** [comment]
Merhaba henuz videosunu cekmedim. Simdiden paylasayim dedim.

6 Oca 2019 Paz 00:07 tarihinde Ozkan SEN <notifications@github.com> şunu
yazdı:

**Comment by ozkansen** [comment]
Bir video da serilerini beğeniyorum hızlı giriş oluyor :)
